version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/jesse0michael/go-rest-assured
    steps:
      - checkout
        - run:
      name: Install Dependencies
      command: |
        go get -u -v -t github.com/Masterminds/glide
        go get -v golang.org/x/tools/cmd/cover
        go get -v github.com/mattn/goveralls
        go get -v github.com/modocache/gover
        make install-deps
      - run:
        name: Build & Test
        command: |
          make all
          make coveralls
